site_name: Pipeline-pocs
repo_url: https://github.com/nousefreak/pipeline-poc
strict: true
theme:
  name: material
  palette:
    primary: blue
  font:
    text: Work Sans
markdown_extensions:
  - codehilite
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - toc:
      permalink: true
nav:
  - Overview: index.md
  - core-concepts.md
  - User Guide:
    - Beginner: beginner
    - Advanced: advanced
  - what.md