name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - uses: actions/setup-go@v1
        with:
          go-version: '1.17'
      - run: pip install mkdocs==1.0.4 mkdocs_material==4.1.1
      - uses: peaceiris/actions-gh-pages@v3
        with:
          keep_files: true
        env:
          PERSONAL_TOKEN: ${{ secrets.GH_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./site
          
