name: Release
on:
  push:
    branches:
      - 'master'
env:
  DOCKER_IMAGE: "ghcr.io/${{ github.repository }}"

jobs:
  release:
    uses: stenic/.github/.github/workflows/release-docker-helm.yaml@main
