name: Release
on:
  push:
    branches:
      - 'master'
env:
  DOCKER_IMAGE: "ghcr.io/${{ github.repository }}"

jobs:
  release:
    uses: NoUseFreak/pipeline-poc/.github/workflows/test/release.yaml@master
